'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with  and , the first terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

sequence = [1, 2]
even_list = []
i = 1

while sequence[i] < 4000000:
    next_number = sequence[i] + sequence[i-1]
    sequence.append(next_number)
    if sequence[i] % 2 == 0:
        even_list.append(sequence[i])
    i = i + 1

print(sum(even_list))